name: crypto-alert-bot
region: nyc

workers:
  - name: alert-worker
    github:
      repo: your-username/your-repo-name
      branch: main
      deploy_on_push: true
    
    source_dir: /
    
    envs:
      - key: TELEGRAM_TOKEN
        value: "8295501088:AAHHwOCuRGhQyvFgnu6Kf0VsQaZEzr133R4"
        scope: RUN_TIME
        type: SECRET
      
      - key: CHAT_ID
        value: "8051329143"
        scope: RUN_TIME
        type: SECRET
      
      - key: VELO_API_KEY
        value: "95dfb6f119584a84aaadae6516c97e43"
        scope: RUN_TIME
        type: SECRET
    
    instance_count: 1
    instance_size_slug: basic-xxs
    
    run_command: python main.py
