name: crypto-alert-bot

workers:
  - name: alert-worker
    github:
      repo: your-username/your-repo-name
      branch: main
      deploy_on_push: true
    
    envs:
      - key: TELEGRAM_TOKEN
        value: "YOUR_TELEGRAM_TOKEN_HERE"
        scope: RUN_TIME
        type: SECRET
      
      - key: CHAT_ID
        value: "YOUR_CHAT_ID_HERE"
        scope: RUN_TIME
        type: SECRET
      
      - key: VELO_API_KEY
        value: "YOUR_VELO_API_KEY_HERE"
        scope: RUN_TIME
        type: SECRET
    
    instance_count: 1
    instance_size_slug: basic-xxs
    
    run_command: python main.py
    
    health_check:
      initial_delay_seconds: 60
      period_seconds: 60
